### ISSUE TITLE
Scores

### ISSUE THREAD

**Issue by monilpat** [apanimesh061/VaderSentimentJava#1]
All my scores are neutral 1 everything else zero? Is this an error that other people have encountered?

**Comment by apanimesh061** [comment]
What are the input strings?

**Comment by monilpat** [comment]
I filtered tweets for Hillary and Trump and all the thousands and thousands of tweets are getting the same score. Do you think you need to remove the special characters (/n /t) from the tweet? Thanks so much for the help and the port!

**Comment by apanimesh061** [comment]
Yes you should remove the special characters like `/r /n /t`. 
If it is possible could post a few tweets so that I check if there any other issue?

**Comment by monilpat** [comment]
"RT @ValaAfshar: Apple has $231.5 billion in cash. It could buy:\n\nUber\nTesla \nTwitter \nAirbnb\nNetflix\nSnapchat\nSpaceX\n\nand still have $21 bi…"

The #largest companies on #earth #inspire us - https://t.co/wxAc60pNhn $wmt $xom $cvx $brk-a $aapl $jwn $aa $xom #MotivationMonday

"$aapl ended AH session up $6.76 (+6.99%)at $103.43 for the day. Not bad at all Apple."

          "$GOOG - Facebook Posts Strong Profit and Revenue Growth--Update https://t.co/5RzsAUG2PR"
Gain from opinions of smart traders &amp; investors $ANZ $JBLU $CSCO https://t.co/O65iooEeaY https://t.co/zjS5zgogEF

Thanks so much!

**Comment by apanimesh061** [comment]
@monilpat  Sometimes a string contains words that are not present in the [https://github.com/apanimesh061/VaderSentimentJava/blob/master/src/main/resources/vader_sentiment_lexicon.txt](lexicon list), so they are ignored.

I suggest you perform some pre-processing on the tweets like remove the URLs, `@mentions`, `#`s etc. Try removing those and see it you see any differences.

**Comment by monilpat** [comment]
Alright sounds good any suggestions on how to do it? I am using Apache Nifi ExtractTest processor currently with regex

**Comment by zevektor** [comment]
Hi, 
I'm having the same issue when I execute your sample snippet code. Any ideas? Do I need extra files or to do any further steps other than cloning your repository?
