### ISSUE TITLE
Incomplete dependency tree

### ISSUE THREAD

**Issue by jottinger** [apanimesh061/VaderSentimentJava#5]
Pulling a simple example means that the downstream project needs to specifically include log4j (which is required by VaderSentimentJava, therefore a valid transitive dependency) as well as Lucene. Both of these should be transitive dependencies.

**Comment by apanimesh061** [comment]
You've already submitted a PR covering this issue. The PR has been merged.

**Comment by jottinger** [comment]
Yes, and thank you - I was just trying to record the various issues as I encountered them so they could each be considered.
