### ISSUE TITLE
Method not defined

### ISSUE THREAD

**Issue by suyashjoshi** [apanimesh061/VaderSentimentJava#9]
I'm getting an error on this line as it seems like analyse() is not defined in the class so can't use this library as much as I would love to.
` sentimentAnalyzer.analyse();`

**Comment by apanimesh061** [comment]
Hi Suyash,
I know this a very late response and apologies for the delay.
I have updated the package and its README so that it becomes easy for any user to use the new versions as a maven dependency.

Thanks.
